exclude = ["black"]
line-length = 127
indent-width = 4
target-version = "py311"

[lint]
extend-select = ["I", "TRY", "UP", "D", "W"]
extend-ignore = ["D213", "D202", "D203", "D213", "UP038", "TRY003"]

[lint.pydocstyle]
convention = "numpy"

[format]
quote-style = "double"
indent-style = "space"

[lint.isort]
force-sort-within-sections = true
known-first-party = [
    "pyecotrend_ista",
]
combine-as-imports = true
split-on-trailing-comma = false
