[tox]
skipsdist = True
envlist = py{311,312,313,314}, format, lint, pre-commit, docstrings, documentation, test-publish
isolated_build = True

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
extras = test
commands =
    pytest --cov=src/pyecotrend_ista --cov-report=xml --cov-report=term-missing {posargs}

[testenv:pre-commit]
skip_install = true
deps =
    pre-commit
commands =
    pre-commit run --all-files -c .pre-commit-config.yaml --show-diff-on-failure

[testenv:lint]
description = Run linters
skip_install = true
deps =
    pylint
    ruff
    dataclasses-json
    requests
commands =
    pylint --rcfile=pyproject.toml {[common] files} tests/
    ruff check {[common] files} tests/ --fix

[testenv:format]
description = Run formatters
skip_install = true
deps =
    ruff
commands =
    ruff format {[common] files} tests/

[testenv:docstrings]
description = Validate docstrings with pydocstyle
skip_install = false
deps =
    pydocstyle
    numpydoc
commands =
    pydocstyle {[common] files} tests/ --convention=numpy

[testenv:documentation]
description = Build the documentation
skip_install = true
extras = doc
setenv =
    MKDOCS_GIT_COMMITTERS_APIKEY = {env:GITHUB_TOKEN}
commands =
    mkdocs build

[testenv:test-publish]
description = Build and publish the test-package to PyPI
skip_install = true
deps =
    build
    twine
commands =
    python -m build
    python -m twine upload --repository testpypi dist/* --non-interactive

[testenv:publish]
description = Build and publish the package to PyPI
skip_install = true
deps =
    build
    twine
commands =
    python -m build
    python -m twine upload dist/*

[common]
files = src/pyecotrend_ista/__init__.py src/pyecotrend_ista/const.py src/pyecotrend_ista/exception_classes.py src/pyecotrend_ista/helper_object_de.py src/pyecotrend_ista/login_helper.py src/pyecotrend_ista/pyecotrend_ista.py src/pyecotrend_ista/__version.py src/pyecotrend_ista/types.py
