name: documentation

on:
  pull_request:
    branches: ["main"]
  merge_group:
    types: [checks_requested]
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ############################
  # BUILDING THE DOCUMENTATION
  ############################
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Cloning repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Configuring Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.13"

      - name: Installing pip packages
        run: |
          pip install .[doc]

      - name: Build documentation
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        run: |
          tox -e documentation

      - name: Publish documentation
        if: github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdocs gh-deploy --force
